### ISSUE TITLE
Extractor not working? 

### ISSUE THREAD

**Issue by norcae2001** [HTV04/mmlc-dac-extractor#1]
I followed all of the instructions in the ReadMe file and installed the latest version of Python. When I double-clicked the .py file in the directory, a command prompt would briefly appear on screen and then disappear. After that, the roms wouldn't appear in the directory. 

I've tried restarting my computer, but it still didn't appear. Not sure if they changed the binaries.

**Comment by HTV04** [comment]
That's weird, it still works for me. Did you install the latest version of Python 3?

**Comment by norcae2001** [comment]
Yeah, I installed Python 3.9.

**Comment by AngusET** [comment]
Same here. v1.1.1.29, verified files' integrity, Python 3.9 (64), with the exact same results. Could this be a region thing? I have no idea

**Comment by HTV04** [comment]
The new version I'm working on has hash detection for the MMLC to verify whether it's the right version or not. I'll release it soon, so maybe this can clear some things up. The current script should still technically output files even if the executable isn't the right one, since it's just looking for offsets in the file.

**Comment by AngusET** [comment]
Yep, I'm sure
![mmlc](https://user-images.githubusercontent.com/74081216/98490750-9c68ad80-2286-11eb-91e1-1a7b2d32ea2f.gif)

**Comment by HTV04** [comment]
This is very, very odd. Can you upload your copy of the file here, so I can compare it to my copy?

**Comment by AngusET** [comment]
https://drive.google.com/file/d/1d8XCY1kHm_dDlJHO3xdF4LqfJu0GtKGL/view?usp=sharing

**Comment by HTV04** [comment]
Thanks. I compared the two files in a hex editor (which would rule out any issues of Python being unable to read the file), and they seem to be identical.

I have no idea what's going on, every device I've tried this script on outputs the ROMs. I'm going to release an updated version of the script soon, so maybe that might work.

**Comment by AngusET** [comment]
I'm afraid I am, yes. Thanks for providing support on this btw

**Comment by HTV04** [comment]
Doubt this would change anything, but does enabling file extensions in File Explorer change anything? I noticed in your GIF that you had them turned off.

**Comment by AngusET** [comment]
The 'File name extensions' checkbox under 'view'? No, no difference.

**Comment by HTV04** [comment]
I just wiped my PC again in order to set up a clean environment for the new Windows 10 update. I'll try installing Python and installing the game again and seeing if the script works properly.

**Comment by AngusET** [comment]
No problem at all, I'm getting something for nothing here

**Comment by HTV04** [comment]
Sorry for being MIA for a while. It still seems to work as intended for me.

Does the original script this was based on work? It won't output valid NES ROMs because the offsets have changed, but if I screwed something up this script should at least output something.

Original script: https://gist.github.com/anpage/b895a34efb0bf1e4a9a4f52228067fa8

**Comment by AngusET** [comment]
I tried this as a different user, and on my old PC, and it doesn't work at all...

**Comment by HTV04** [comment]
anpage's script or mine?

**Comment by AngusET** [comment]
Both.

**Comment by HTV04** [comment]
I don't know what the issue could be, I tried it several times and both scripts work. I don't want to say this is an issue on your end, because it looks like Windows is calling the right executable, py.exe.

I made a debug version of the script, which begins by outputting the current directory (in case it's reading/writing files somewhere it shouldn't) and pauses between important parts of the script. If any errors are occurring between the important parts, we'll know where the script is stopping. If the script is successful, it should get all the way to "Done."

Here it is: [mmlc-extractor.zip](https://github.com/HTV04/MMLC-Extractor/files/5759171/mmlc-extractor.zip)

**Comment by AngusET** [comment]
Well, it's [definitely not regional,](https://www.reddit.com/r/pcgaming/comments/m4qe0g/redownloading_from_a_different_region_on_steam/?utm_source=share&utm_medium=web2x&context=3) for what it's worth. Not sure if that was a possibility to begin with, but.

**Comment by MalikTH** [comment]
Heya, coming in with a solution. When installing Python, make sure you add it to your system's PATH variable by checking the checkbox:

![image](https://user-images.githubusercontent.com/8645405/113488149-3a555280-948a-11eb-9755-c571fa4969fe.png)

I was also having issues with using the extractor, and I came across this solution on my own. I cannot fathom why it's an optional feature, but I digress.

**Comment by AngusET** [comment]
We have a solution!

**Comment by HTV04** [comment]
Finally! No wonder I wasn't able to reproduce the issue. I wonder why not having Python in the path causes issues, though. Maybe it's the shebang. I'll check it out.
